### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-rpm-porting#10]
Current copyright notice says @torsava. Since others including me contributed, I suggest to make it one of the following:
- Red Hat Inc.
- @torsava and other PRM Porting Guide contributors (link to GitHub repo contributors)

It would also be good if this thing was somehow Creative Commons (BY-SA maybe) and the examples Public Domain, otherwise it is useless for others, legally speaking.

**Comment by torsava** [comment]
Looks all right? I also changed the copyright in the footer to "Red Hat, Inc.".

**Comment by hroncok** [comment]
Awesome! Adding one more thing in a PR. I know I shouldn't be working right now, but being a license nazi, I cannot help myself :)
