### ISSUE TITLE
Porting an application and a module in one package

### ISSUE THREAD

**Issue by torsava** [fedora-python/python-rpm-porting#12]
@hroncok , @encukou I encountered a bit of a problem.

For the section "[Porting an application and a module in one package](http://python-rpm-porting.readthedocs.org/en/latest/application-modules.html)" we have a package `python-example` that contains both a Python module and an Python version-independent application.

In compliance with the guidelines we have to package the Python 3 version of the application, and therefore we can include it in the Python 3 subpackage or create a new subpackage named just `example` that will depend on the Python 3 subpackage.

The problem is, the users that have `python-example` currently installed: If they do `dnf update` the dnf will replace the `python-example` package with the `python2-example` package (as it contains the currently active %python_provide macro), and therefore will lose the bundled application from their system.

A subsequent problem is also that after this change the packager will have to find all packages that depend on this package, figure out which of them depend on the application, and then change the Requires tag in all those packages to require the new Python 3 subpackage or the application subpackage.

I can't find a better way around this, any idea?

**Comment by hroncok** [comment]
If another package requires the app, it should require /usr/bin/app instead
of the python-something package. The packager should be aware of packages
depending on their package and make sure they got it right.

**Comment by torsava** [comment]
Should it? The guidelines generally [advise against using file dependencies](https://fedoraproject.org/wiki/Packaging:Guidelines#File_Dependencies).

So should I write in the guide that the package should check all the packages that depend on the one being ported, check whether they depend on the package but want to depend on the application, contact them to try to resolve it?

I'm honestly thinking if we shouldn't just advise them to include the executable in both the subpackages, as that would save them a hell of a porting headache even though it's not following the guidelines to the letter.

And do you think I should advise creating a separate app subpackage, or including the executable in the Python 3 subpackage?

**Comment by hroncok** [comment]
Well, files in bin are also as virtual provides, so this does not apply
here.

Also, how would you provide the app in both? The same as in python tool
group? We want to avoid that.

No need for separate package if it wasn't present already before porting.

**Comment by torsava** [comment]
> Well, files in bin are also as virtual provides, so this does not apply
> here.

I'm not arguing that, I'm just arguing that the Guidelines (as imperfect as they may be) discourage the use of File Dependencies and don't mention the /usr/bin exception, so we shouldn't be counting on packages requiring the executable directly instead of the package.

> Also, how would you provide the app in both? The same as in python tool
> group? We want to avoid that.

Yeah, you're right. Ok then, that'll be one interesting section of the guide.

> No need for separate package if it wasn't present already before porting.

Good to hear, because that's how I've already written it. :)

**Comment by torsava** [comment]
> If another package requires the app, it should require /usr/bin/app instead
> of the python-something package.

How should I justify this in the guide? When is it better to require the executable directly? The guidelines mention only "If the files you need are prone to moving between packages of different names, it can be useful to depend on those files directly." which I don't think applies here.

Perhaps: Is it advisable to depend on the executable directly if it is part of a package which also includes a Python module?

**Comment by hroncok** [comment]
BTW https://fedoraproject.org/wiki/Packaging:ReviewGuidelines

> SHOULD: If the package has file dependencies outside of /etc, /bin, /sbin, /usr/bin, or /usr/sbin consider requiring the package which provides the file instead of the file itself. 
> 
> Perhaps: Is it advisable to depend on the executable directly if it is part of a package which also includes a Python module?

It is advisable to depend on the executable directly to make sure the right package is pulled in, regardless of where the executable resides.

**Comment by torsava** [comment]
Hm, having read the guidelines as they are, I have always depended on packages, not files, and what I've seen of the spec files in the wild, requiring files is not very common. Someone should really update the guidelines.

All right, I'll try to convey this in the guide.
