### ISSUE TITLE
Shebangs

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-rpm-porting#15]
Shebangs are often forgotten and drag python2 dependency.

I didn't find anything about this in the guide, maybe we can mention it?

Note that proper installs using setup.py might not have such problem, but other means of installation probably will. So this might go near the note about custom install scripts.

**Comment by torsava** [comment]
Ok, so I'll mention in the Application section that you should change the shebangs from python to python3. But what about the other sections where both python versions are packaged? Just remove all the shebangs?

**Comment by torsava** [comment]
Also, should I mention that they ought to change "/usr/bin/env python(3)" into "/usr/bin/python(3)"? It is technically beyond the scope of the porting effort.

**Comment by hroncok** [comment]
> But what about the other sections where both python versions are packaged? Just remove all the shebangs?

"Executables" in /usr/bin /usr/sbin /usr/libexec should have shebangs, stuff in site-packages should not.

> Also, should I mention that they ought to change "/usr/bin/env python(3)" into "/usr/bin/python(3)"? It is technically beyond the scope of the porting effort.

You can mention it while there. Good idea to mention automatic shebeng require thing as well.

**Comment by torsava** [comment]
> "Executables" in /usr/bin /usr/sbin /usr/libexec should have shebangs, stuff in site-packages should not.

True, but you still encounter it often. And it will drag in the Python dependency nonetheless so I think it would be beneficial to mention in the guide to check for that.

> Good idea to mention automatic shebeng require thing as well.

You mean that RPM will look at the shebangs and infer dependency on Python, or are you referring to something else?

**Comment by hroncok** [comment]
> You mean that RPM will look at the shebangs and infer dependency on Python,

yes

**Comment by torsava** [comment]
It's a rather complex issue so I'd be grateful if you took a look at it, Miro.

**Comment by hroncok** [comment]
I've put some inline comments.

BTW I'd suggest to do a pull request if you want comments, rather than pushing the change to master and asking me later. I know it feels weird to do a pull request on you own repo, but I have OCD about issues, commits and stuff :D

**Comment by torsava** [comment]
Thank you for the comments!

And the pull request is a great idea, I didn't even know that could be done! :) I'll definitely use it in the future.
