### ISSUE TITLE
%py*_install sets shebangs automatically

### ISSUE THREAD

**Issue by encukou** [fedora-python/python-rpm-porting#16]
In many cases, it's not necessary to rewrite shebangs in %prep, because setuptools sets shebangs of scripts it installs. So the `find`/`sed` lines should only be necessary if [setuptools entry points](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation) are not used, for example if executables are copied to `/usr/bin` directly using `cp` or `make`.

**Comment by torsava** [comment]
Discussion on this topic can be found here: https://github.com/fedora-python/python-rpm-porting/commit/dc81f98d148695c4bbf5f4f2aa7c89d58aeca522#diff-e2a618a8a708e2d2fab2a9e51e3eff8fR26
