### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-rpm-porting#6]
How does having a plugin system justifies having both legacy Python and Python 3 version packaged?

**Comment by torsava** [comment]
Well, if your plugins can be written in both Python 2 and 3, then it does, doesn't it? I'll expand the description thus if you agree.

**Comment by hroncok** [comment]
OK, give me an real world example.

Cause I don't see why we would like to have 2 versions of GIMP juts because it has plugins in Python (that's true) and both versions are supported (that might not be the case with GIMP, so imagine it).

**Comment by hroncok** [comment]
Yes, but it doesn't fit into that category, does it? See python-pygments. No Python tool.
