### ISSUE TITLE
Makefiles and such

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-rpm-porting#9]
I've seen applications written in Python that used Makefiles to install themselves.
In this guide, we assume every Python package is nicely done invoking the `setup.py`. Do we want to cover any other case? At least in some general manner?

**Comment by torsava** [comment]
I can mention that if the old specfile runs some non-python script to install, such as a makefile, you'll have to adjust it on your own.

I wouldn't be confortable writing a section on that as my knowledge is very limited in that area.

**Comment by hroncok** [comment]
> I can mention that if the old specfile runs some non-python script to install, such as a makefile, you'll have to adjust it on your own.

Yes, something like that will work.
